name             'fieri'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@getchef.com'
license          'Apache v2.0'
description      'Installs/Configures fieri'
long_description 'Installs/Configures fieri'
version          '0.0.1'

depends          'apt'
depends          'redisio'
